name       : fribidi
version    : 1.0.10
release    : 8
source     :
    - https://github.com/fribidi/fribidi/releases/download/v1.0.10/fribidi-1.0.10.tar.xz : 7f1c687c7831499bcacae5e8675945a39bacbad16ecaa945e9454a32df653c01
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Implementation of the Unicode Bidirectional Algorithm
description: |
    GNU FriBidi is an implementation of the Unicode Bidirectional Algorithm, known is "bidi" which specifies the positioning of characters in text.
patterns   :
    - devel : /usr/bin/fribidi
emul32     : yes
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
