name       : fribidi
version    : 1.0.2
release    : 5
source     :
    - https://github.com/fribidi/fribidi/archive/v1.0.2.tar.gz : 1609083ac93fd60078c60ecdd60b61aff86855eb33e09acced579f110e41b04d
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Implementation of the Unicode Bidirectional Algorithm
description: |
    GNU FriBidi is an implementation of the Unicode Bidirectional Algorithm, known is "bidi" which specifies the positioning of characters in text.
patterns   :
    - devel : /usr/bin/fribidi
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
