name        : fribidi
version     : 0.19.7
release     : 4
source     :
    - http://fribidi.org/download/fribidi-0.19.7.tar.bz2 : 08222a6212bbc2276a2d55c3bf370109ae4a35b689acbc66571ad2a670595a8e
license     : LGPL-2.1
summary     : Implementation of the Unicode Bidirectional Algorithm
description : |
    GNU FriBidi is an implementation of the Unicode Bidirectional Algorithm, known is "bidi" which specifies the positioning of characters in text.
patterns   :
    - devel: /usr/bin/fribidi
setup      : |
    %configure --with-glib=yes
build      : |
    %make
install    : |
    %make_install
