name       : fribidi
version    : 1.0.5
release    : 7
source     :
    - https://github.com/fribidi/fribidi/archive/v1.0.5.tar.gz : aee3a93d081c293eaca9157700f17dc780a0b6674bc911decc5aaa43aec9abd7
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Implementation of the Unicode Bidirectional Algorithm
description: |
    GNU FriBidi is an implementation of the Unicode Bidirectional Algorithm, known is "bidi" which specifies the positioning of characters in text.
patterns   :
    - devel : /usr/bin/fribidi
emul32     : yes
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
