name       : fribidi
version    : 1.0.12
release    : 9
source     :
    - https://github.com/fribidi/fribidi/releases/download/v1.0.12/fribidi-1.0.12.tar.xz : 0cd233f97fc8c67bb3ac27ce8440def5d3ffacf516765b91c2cc654498293495
homepage   : https://github.com/fribidi/fribidi
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Implementation of the Unicode Bidirectional Algorithm
description: |
    GNU FriBidi is an implementation of the Unicode Bidirectional Algorithm, known is "bidi" which specifies the positioning of characters in text.
patterns   :
    - devel : /usr/bin/fribidi
emul32     : yes
setup      : |
    %meson_configure -Ddocs=false
build      : |
    %ninja_build
install    : |
    %ninja_install
check      : |
    %ninja_check
